---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kube-logging
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    xpack.encryptedSavedObjects.encryptionKey: "12345678912345678912345678912345"
    elasticsearch:
      hosts: ${ELASTICSEARCH_HOSTS}
      username: elastic
      password: kibana
    server.ssl.enabled: true
    server.ssl.certificate: /usr/share/kibana/config/my-kibana.crt
    server.ssl.key: /usr/share/kibana/config/my-kibana.key
    elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/ca.crt" ]
    elasticsearch.ssl.verificationMode: certificate

---
